# Generated by Django 3.2.12 on 2023-01-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productDesc', models.CharField(max_length=300)),
                ('pubDate', models.DateField()),
            ],
        ),
    ]
